# Generated by Django 3.2.10 on 2023-07-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Backend', '0002_productdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='Description',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
