# Generated by Django 3.2.10 on 2023-07-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Backend', '0003_alter_productdb_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='Pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
