# Generated by Django 3.2.10 on 2023-07-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Frontend', '0002_cartdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Password', models.CharField(blank=True, max_length=100, null=True)),
                ('Confirm_password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
